import { mkdirSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { MetroConfig } from "metro-config";
import { withUniwindConfig } from "uniwind/metro";
import {
  THEME_COLOR_PREFIX,
  THEME_COLORS,
  THEME_SCHEMES,
  themeColorNames,
} from "../theme/tokens.js";

const PACKAGE_ROOT = realpathSync(
  path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../.."),
);
const PACKAGE_MANIFEST_PATH = path.join(PACKAGE_ROOT, "package.json");
const STYLES_SPECIFIER = "#/internal/styles";
const ENGINE_PACKAGE = "uniwind";
const GENERATED_DIR_NAME = ".invid-ui";
const GENERATED_STYLES_NAME = "styles.css";
const GENERATED_TYPES_NAME = "engine.d.ts";
const GENERATED_IGNORE_NAME = ".gitignore";
const GENERATED_IGNORE_CONTENT = "*\n";

type ResolveRequest = NonNullable<
  NonNullable<MetroConfig["resolver"]>["resolveRequest"]
>;
const requireFromPackage = createRequire(PACKAGE_MANIFEST_PATH);

function toImportPath(fromDir: string, target: string) {
  const relative = path
    .relative(fromDir, realpathSync(target))
    .split(path.sep)
    .join("/");
  return relative.startsWith(".") ? relative : `./${relative}`;
}

function renderStyles(generatedDir: string) {
  const engineDir = path.dirname(
    requireFromPackage.resolve(`${ENGINE_PACKAGE}/package.json`),
  );
  const imports = [
    requireFromPackage.resolve("tailwindcss/index.css"),
    path.join(engineDir, "uniwind.css"),
    requireFromPackage.resolve("heroui-native/styles"),
  ].map((target) => `@import "${toImportPath(generatedDir, target)}";`);
  const source = `@source "${toImportPath(generatedDir, path.join(PACKAGE_ROOT, "dist"))}";`;
  const aliases = themeColorNames().map(
    (color) =>
      `  ${THEME_COLOR_PREFIX}${color}: var(${THEME_COLORS[color].engineVariable});`,
  );
  const variants = THEME_SCHEMES.map((scheme) => {
    const declarations = themeColorNames().map(
      (color) =>
        `      ${THEME_COLORS[color].engineVariable}: ${THEME_COLORS[color][scheme]};`,
    );
    return `    @variant ${scheme} {\n${declarations.join("\n")}\n    }`;
  });

  return `/* Generated by @invid/ui. Do not edit; changes are overwritten. */
${imports.join("\n")}
${source}

@theme inline static {
${aliases.join("\n")}
}

@layer theme {
  :root {
${variants.join("\n\n")}
  }
}
`;
}

function writeIfChanged(filePath: string, content: string) {
  let current: string | undefined;
  try {
    current = readFileSync(filePath, "utf8");
  } catch {
    current = undefined;
  }
  if (current !== content) {
    writeFileSync(filePath, content);
  }
}

function isEngineRequest(moduleName: string) {
  return (
    moduleName === ENGINE_PACKAGE || moduleName.startsWith(`${ENGINE_PACKAGE}/`)
  );
}

/**
 * Configures Metro for `@invid/ui`. Apply it as the outermost wrapper of the
 * Metro config.
 */
export function withINVIDUI(config: MetroConfig): MetroConfig {
  const projectRoot = realpathSync(config.projectRoot ?? process.cwd());
  const generatedDir = path.join(projectRoot, GENERATED_DIR_NAME);
  const stylesPath = path.join(generatedDir, GENERATED_STYLES_NAME);
  mkdirSync(generatedDir, { recursive: true });
  writeIfChanged(
    path.join(generatedDir, GENERATED_IGNORE_NAME),
    GENERATED_IGNORE_CONTENT,
  );
  writeIfChanged(stylesPath, renderStyles(generatedDir));

  const previousResolveRequest = config.resolver?.resolveRequest;
  const packagePrefix = `${PACKAGE_ROOT}${path.sep}`;

  const resolveRequest: ResolveRequest = (context, moduleName, platform) => {
    if (
      moduleName === STYLES_SPECIFIER &&
      context.originModulePath.startsWith(packagePrefix)
    ) {
      return { type: "sourceFile", filePath: stylesPath };
    }

    const resolve = previousResolveRequest ?? context.resolveRequest;
    const nextContext = isEngineRequest(moduleName)
      ? { ...context, originModulePath: PACKAGE_MANIFEST_PATH }
      : context;
    return resolve(nextContext, moduleName, platform);
  };

  return withUniwindConfig(
    { ...config, resolver: { ...config.resolver, resolveRequest } },
    {
      cssEntryFile: path.relative(process.cwd(), stylesPath),
      dtsFile: path.relative(
        process.cwd(),
        path.join(generatedDir, GENERATED_TYPES_NAME),
      ),
    },
  );
}
